matrix:
  include:
    # Check if firmware compiles
    - language: minimal
      dist: xenial
      sudo: true
      before_install:
       - sudo apt-get update
       - sudo apt-get install -y sdcc cmake 
       - cd ./software/Firmware
      script:
       - sdcc --version
       - mkdir build_directory
       - cd build_directory
       - cmake -DCMAKE_SYSTEM_NAME=Generic -DCMAKE_C_COMPILER=sdcc ..
       - make VERBOSE=1

    # Check if latex files are correct
    - language: minimal
      dist: xenial
      sudo: true
      before_install:
       - sudo apt-get update
       - sudo apt-get install -y texlive-latex-base texlive-latex-extra texlive-extra-utils poppler-utils
       - cd ./documentation/diagrams
      script:
       - chmod +x ./creatediagrams.sh
       - ./creatediagrams.sh

    # Use cppcheck to check statically C code
    - language: minimal
      dist: xenial
      sudo: true
      before_install:
       - sudo apt-get update
       - sudo apt-get install -y cppcheck 
       - cd ./software/Firmware
      script:
       - cppcheck  --enable=all --quiet --error-exitcode=1 Src/* Inc/* 

    # Use pyflakes (or other tool) to check statically Python code
    - language: python
      dist: xenial
      sudo: true
      before_install:
       - sudo apt-get update
       - sudo apt-get install -y python3-pip
       - pip3 install pyflakes
       - cd ./software/DataAcquisitionFromDevice
      script:
       - pyflakes *.py

