matrix:
  include:
    # check if firmware compiles
    - language: minimal
      dist: xenial
      sudo: true
      before_install:
       - sudo apt-get update
       - sudo apt-get install -y sdcc cmake 
       - cd ./software/Firmware
      script:
       - sdcc --version
       - mkdir build_directory
       - cd build_directory
       - cmake -DCMAKE_SYSTEM_NAME=Generic -DCMAKE_C_COMPILER=sdcc ..
       - make VERBOSE=1

    - language: r
      sudo: false
      cache: packages
      dist: xenial
      warnings_are_errors: false
      before_install:
       - cd ./software/DataAcquisitionFromDevice/packages/CSV2Diagrams

    # check if latex files are correct
    - language: minimal
      dist: xenial
      sudo: true
      before_install:
       - sudo apt-get update
       - sudo apt-get install -y texlive-latex-base texlive-latex-extra texlive-extra-utils poppler-utils
       - cd ./documentation/diagrams
      script:
       - chmod +x ./creatediagrams.sh
       - ./creatediagrams.sh

    # Use cppcheck (or other tool) to check statically C code
    - language: minimal
      dist: xenial
      sudo: true
      before_install:
       - sudo apt-get update
       - sudo apt-get install -y sdcc cmake 
       - cd ./software/Firmware
      script:
       - cppcheck  --enable=all --quiet --error-exitcode=1 Src/* Inc/* 
    
