strictness: veryhigh

pydocstyle:
  disable:
    - D212   # Multi-line docstring summary should start at the first line
    - D211   # Multi-line docstring summary should start at the first line (alternative)
    - D400   # First line should end with a period
    - D415   # First line should end with a period, question mark, or exclamation point
    - D202   # No blank lines allowed after function docstring
    - D201   # No blank lines allowed before function docstring
    - D203   # 1 blank line required before class docstring
    - D213   # Multi-line docstring summary should start at the second line
    - D406   # Section name should end with a newline
    - D407   # Missing dashed underline after section
    - D413   # Missing blank line after last section
  options:
    max-line-length: 105  # Should match pycodestyle/pylint

pycodestyle:
  options:
    max-line-length: 105
    ignore:
      - E501  # Line too long (handled by max-line-length)

pylint:
  options:
    max-line-length: 105
    disable:
      - missing-module-docstring       # D100
      - missing-class-docstring        # D107
      - missing-function-docstring     # D102
      - invalid-name                   # N816 and other naming conventions
      - attribute-defined-outside-init # Attribute defined outside __init__