{% extends 'default.puml' %}

{% block preamble %}
' Set the layout direction (left to right or top to bottom)
left to right direction
{% endblock %}

{% block content %}

{% endblock %}

{% block layout %}
' Ensure "Device" is placed below "Driver"
together {
    namespace Driver
    down
    namespace Device
}
{% endblock %}
