name: CI Pipeline

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  build-docker-image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.tag-image.outputs.image-tag }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build Docker Image
        run: docker-compose build

      - name: Tag Docker Image
        id: tag-image
        run: |
          IMAGE_TAG=ci-image-$(date +%s)
          echo "image-tag=$IMAGE_TAG" >> $GITHUB_OUTPUT
          docker tag $(docker-compose images -q app) $IMAGE_TAG

      - name: Save Docker Image
        run: docker save -o image.tar ${{ steps.tag-image.outputs.image-tag }}

      - name: Upload Docker Image
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: image.tar

  parallel-tasks:
    name: Parallel Tasks
    needs: build-docker-image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        type: [c-static, python-static, firmware]
      fail-fast: false  # Continue other jobs if one fails
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Download Docker Image
        uses: actions/download-artifact@v4
        with:
          name: docker-image
          path: .

      - name: Load Docker Image
        run: docker load -i image.tar

      - name: Start Docker Compose
        run: |
          docker-compose up -d --no-build

      - name: Run Analysis or Build
        run: |
          case "${{ matrix.type }}" in
            c-static)
              docker-compose exec -T app bash -c "dos2unix /workspace/ContinuousIntegration/run_c_static_code_analysis.sh && bash /workspace/ContinuousIntegration/run_c_static_code_analysis.sh"
              docker cp app:/workspace/build/C_Lint_ReportApplicationOnly.txt .
              docker cp app:/workspace/build/C_Lint_ReportFull.txt .
              ;;
            python-static)
              docker-compose exec -T app bash -c "dos2unix /workspace/ContinuousIntegration/run_python_static_code_analysis.sh && bash /workspace/ContinuousIntegration/run_python_static_code_analysis.sh"
              docker cp app:/workspace/build/python_lint_report .
              ;;
            firmware)
              docker-compose exec -T app bash -c "cd /workspace/build && cmake ../Software/Firmware/ && make -j$(nproc)"
              docker cp app:/workspace/build/IonizationChamber.cdb .
              docker cp app:/workspace/build/IonizationChamber.lk .
              docker cp app:/workspace/build/IonizationChamber.ihx .
              docker cp app:/workspace/build/IonizationChamber.map .
              ;;
          esac

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.type }}-artifacts
          path: |
            ${{ matrix.type == 'c-static' && 'C_Lint_Report*.txt' || '' }}
            ${{ matrix.type == 'python-static' && 'python_lint_report' || '' }}
            ${{ matrix.type == 'firmware' && 'IonizationChamber.*' || '' }}

      - name: Clean Up Containers
        if: always()
        run: docker-compose down