name: CI Pipeline

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

# Define common steps as YAML anchor (corrected structure)
docker-setup: &docker-setup
  - name: Checkout Code
    uses: actions/checkout@v3

  - name: Install Docker Compose
    run: |
      sudo apt-get update
      sudo apt-get install -y docker-compose

  - name: Build and Start Docker Compose
    run: |
      docker-compose up -d --build

jobs:
  run-c-static-analysis:
    name: Run C Static Analysis
    runs-on: ubuntu-latest
    steps:
      - *docker-setup
      - name: Run C Static Analysis
        run: |
          docker-compose exec -T app bash -c "source /workspace/venv/bin/activate && cd /workspace/build && cmake .. && make cstatic"

      - name: Copy C Analysis Reports to Host
        run: |
          docker cp app:/workspace/DevOps/BuildArtifacts/CStaticAnalysis .

      - name: Archive C Analysis Reports
        uses: actions/upload-artifact@v4
        with:
          name: c-lint-reports
          path: CStaticAnalysis

      - name: Clean Up Containers
        run: |
          docker-compose down

  run-python-static-analysis:
    name: Run Python Static Analysis
    runs-on: ubuntu-latest
    steps:
      - *docker-setup
      - name: Run Python Static Analysis
        run: |
          docker-compose exec -T app bash -c "source /workspace/venv/bin/activate && cd /workspace/build/ && cmake .. && make pystatic"

      - name: Copy Python Analysis Reports to Host
        run: |
          docker cp app:/workspace/DevOps/BuildArtifacts/PythonStaticAnalysis .

      - name: Archive Python Analysis Reports
        uses: actions/upload-artifact@v4
        with:
          name: python-lint-reports
          path: PythonStaticAnalysis

      - name: Clean Up Containers
        run: |
          docker-compose down

  build-firmware:
    name: Build Firmware
    runs-on: ubuntu-latest
    steps:
      - *docker-setup
      - name: Build Firmware
        run: |
          docker-compose exec -T app bash -c "cd /workspace/build && cmake ../Software/Firmware/ && make -j$(nproc)"

      - name: Copy Firmware Files to Host
        run: |
          docker cp app:/workspace/build/IonizationChamber.cdb .
          docker cp app:/workspace/build/IonizationChamber.lk .
          docker cp app:/workspace/build/IonizationChamber.ihx .
          docker cp app:/workspace/build/IonizationChamber.map .

      - name: Archive Firmware Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware-build-artifacts
          path: |
            IonizationChamber.cdb
            IonizationChamber.lk
            IonizationChamber.ihx
            IonizationChamber.map

      - name: Clean Up Containers
        run: |
          docker-compose down

  docs-coverage:
    name: Documentation Coverage
    runs-on: ubuntu-latest
    steps:
      - *docker-setup
      - name: Generate Documentation
        run: |
          docker-compose exec -T app bash -c "source /workspace/venv/bin/activate && cd /workspace/build/ && cmake .. && make docs"

      - name: Copy Documentation Coverage Report
        run: |
          docker cp app:/workspace/DevOps/BuildArtifacts/DocsCoverage .

      - name: Archive Documentation Coverage
        uses: actions/upload-artifact@v4
        with:
          name: docs-coverage-report
          path: DocsCoverage

      - name: Clean Up Containers
        run: |
          docker-compose down